### ISSUE TITLE
Plugin does't highlight anything once installed

### ISSUE THREAD

**Issue by wladston** [vim-pandoc/vim-criticmarkup#2]
Hello,

Once I install this plugin, absolutely nothing happens.

<img width="274" alt="screen shot 2015-12-02 at 18 34 04" src="https://cloud.githubusercontent.com/assets/356660/11543379/696623c8-9923-11e5-8e5d-62b0bdb443c0.png">

I tried uninstalling all plugins except vim-padoc ones, I tried many colorschemes, but nothing seems to make it work. Help?

**Comment by fmoralesc** [comment]
Is the file named `teste.pandoc`? If so, it's very likely that the filetype is not properly set. Try:
~~~ vim
:set filetype=pandoc
~~~

**Comment by wladston** [comment]
@fmoralesc, thanks for the reply :)

The filetype is `pandoc` for sure, it shows in the status bar. Running the set filetype makes no difference (when I issue `set filetype` is says back `filetype=pandoc`).

**Comment by wladston** [comment]
@fmoralesc in addition, the pandoc "conceal" syntax works, and the command :Critic also works. The problem is specifically the highlight.

**Comment by wladston** [comment]
I figured it out.

This plugin only configures hl for the GUI Vim, not for the terminal.

When I issue
```
:hi criticAdd ctermbg=green
```
it starts showing a green background for additions :)

**Comment by fmoralesc** [comment]
Ah! I guess I never even tried the plugin in the terminal when I used it (or tested it in neovim, where the gui colors can be used instead of the cterm ones).

**Comment by fmoralesc** [comment]
I just pushed some changes, please test them. Feel free to suggest new values.

**Comment by wladston** [comment]
![image](https://cloud.githubusercontent.com/assets/356660/11544415/d8c53574-9928-11e5-93c8-5f099049e91f.png)
Much better! But the legibility is a bit off, specially for the yellow and green bgs. The blue bg has a great legibility :)

**Comment by fmoralesc** [comment]
I can't test properly atm, so if you find better looking colors I'll
include them.

**Comment by wladston** [comment]
Just issued a pull request with the closest xterm colors for background and foreground.

**Comment by fmoralesc** [comment]
I merged it, thanks for that ;)

**Comment by wladston** [comment]
Thanks for the merge :) I only use the terminal vim. As soon as they add neovim to mac ports, and my favourite plugins work on neovim, I'll also switch.
